spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-test
    username: barqifuady
    password:
    driver-class-name: org.postgresql.Driver

  application:
    openapi:
      dev-url: http://localhost:8080

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
